### ISSUE TITLE
Unreliable download process with about 50% failure rate.

### ISSUE THREAD

**Issue by pauelm** [walaaaah/ytMassDownloader#1]
Great looking UI, and I really like the search / preview feature as well!

Unfortunately, after running several tests, I discovered that the download process is unreliable, and operates at about a 50% failure rate.  Although the failure rate does appear to be a little higher for HD videos, the failure rate for other types of videos is almost as high.  

I tried several different types of videos, different lengths, different quality levels, etc., but I was unable to find any consistent patterns.  However, for any failures I received, I could repro them 100%, regardless of the video involved.

Here are some examples that always failed:

https://www.youtube.com/watch?v=KPJybGJe3_M&list=PLz58QJ68R9CSw5YUr1oAjD9dXDj8qbkRw
https://www.youtube.com/watch?v=TIeXl6K6fqw
https://www.youtube.com/watch?v=NQNAdgo91JE
https://www.youtube.com/watch?v=YLuZjpxmsZQ
https://www.youtube.com/watch?v=ZvSQ3Cc8Umg

I have also been testing with a completely different solution, where all the above videos were successfully downloaded, and the tests passed multiple times.  However, the video quality level is lower.

The error thrown is just a basic "Download finished with 1 error!", with no other details.  It is not 100% consistent on the timing as to when this error gets thrown, but the area that I have narrowed it down to is usually within this if statement structure:

if (qualityInt == 0) { vidStreamInfo = videoStreamInfoList.First(); audioStreamInfo = audioStreamInfoList.First(); }
                        else if (qualityInt == 2) { vidStreamInfo = videoStreamInfoList.Last(); audioStreamInfo = audioStreamInfoList.Last(); }
                        else { vidStreamInfo = videoStreamInfoList.ElementAt((int)(videoStreamInfoList.Count() / 2)); audioStreamInfo = audioStreamInfoList.ElementAt((int)(audioStreamInfoList.Count() / 2)); }

Let me know if there is any additional information that might be useful, and I will see if I can dig it up for you.

Thanks,

Paul

**Comment by hdngo** [comment]
Sorry for the late reply, high school has taken a big toll on my available free time. This is a confirmed problem with YoutubeExplode version 4.7.10. Updating the dependencies and recompiling should get it working.
